name: Maven Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # ou adoptium
          java-version: '17'

      # Étape 3 : Lister les fichiers pour vérifier `pom.xml`
      - name: List files
        run: ls -R

      # Étape 4 : Vérifier la présence du fichier pom.xml
      - name: Ensure pom.xml exists
        run: |
          if [ ! -f pom.xml ]; then
            echo "Error: pom.xml not found!"
            exit 1
          fi
      # Étape 5 : Construire le projet avec Maven
      - name: Build with Maven
        run: mvn clean install

      # Étape 6 : Exécuter les tests Maven
      - name: Run Tests
        run: mvn test

      # Étape 7 : Uploader les résultats des tests (optionnel)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports # Dossier par défaut des rapports Maven
