name: Run Java Tests

on:
  pull_request:
    branches:
      - main  # Target branch for the tests
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'
          java-package: 'jdk'  # Ensures JDK installation
          check-latest: false  # Prevents checking for the latest version
          server-id: 'github'  # The server ID used for repository authentication
          server-username: ${{ github.actor }}  # GitHub actor (your GitHub username)
          server-password: ${{ secrets.GITHUB_TOKEN }}  # Securely store and use the GITHUB_TOKEN
          overwrite-settings: true  # Allows overwriting Maven settings
          job-status: success  # Specifies the status to indicate successful job completion

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests  # Skips tests during the installation phase

      - name: Run Tests
        run: mvn test  # Run tests with Maven
