name: Run Java Tests

on:
  pull_request:
    branches:
      - main  # Target branch for the tests
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'
          java-package: 'jdk'  # Ensures JDK installation
          check-latest: false  # Prevents checking for the latest version

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests  # Skips tests during the installation phase

      - name: Run Tests
        run: mvn test  # Run tests with Maven
